#ifndef BNEWS_DEFAULTS_HPP
#define BNEWS_DEFAULTS_HPP

#define DEFAULT_DOLOG       FALSE
#define DEFAULT_DOSORT      FALSE
#define DEFAULT_DOSTDIO     FALSE
#define DEFAULT_DOVERBOSE   FALSE
#define DEFAULT_DOVERIFY    FALSE
#define DEFAULT_KWANTED     1024
#define DEFAULT_MINBPS      0
#define DEFAULT_PORT        119

#endif // BNEWS_DEFAULTS_HPP
